version: 1.0.{build}
branches:
  only:
    - main

environment:
  nodejs_version: '14'

install:
  # - ps: Install-Product node $env:nodejs_version
  # - npm install
  - npm install -g yarn
  - yarn install

build_script:
  # - npm run build
  - yarn build

test_script:
  # - npm run test
  - yarn test

# deploy_script:
#   - npm run deploy

# artifacts:
#   - path: dist
#     name: $(ProjectName)

# deploy:
#   provider: GitHub
#   username: $(github_username)
#   password: 
#     secure: $(github_token)
#   repository: $(github_repo)
#   on:
#     branch: main